### PR TITLE
Fix terraform version pinning

### LINKED ISSUE #21: nubis-skel terraform/main.tf version pinning
Update module ref= during release

### LINKED ISSUE #87: Make sure versions are correctly pinned during release
Ref: mozilla-itcloud/maintenance-project/issues/30

### PR DESCRIPTION
**Pull request by tinnightcap**
- Ride along for issue creation erant error message

Closes #21
Closes #87

Closes mozilla-itcloud/maintenance-project/issues/30

### CODE REVIEW

File: bin/edit.sh [hunk 1]
```diff
@@ -20,7 +20,8 @@ edit_project_json () {
         local _EDIT_PROJECT_VERSION; _EDIT_PROJECT_VERSION=$(grep -c 'project_version' "${_FILE}")
         if [ "${_EDIT_PROJECT_VERSION:-0}" -ge 1 ]; then
             log_term 0 "Updating project_version in \"${_FILE}\"." -e
-            # Preserve any build data appended to the version
+            log_term 3 "File: '${BASH_SOURCE[0]}' Line: '${LINENO}'"
+           # Preserve any build data appended to the version
```
Comment (gozer) [inline bin/edit.sh]: Comment doesn't line up correctly

**Review by gozer — CHANGES_REQUESTED** [review]

File: bin/git_functions.sh [hunk 2]
```diff
@@ -589,9 +593,15 @@ check_in_changes () {
     if [ ${CONTINUE:-y} == "Y" ] || [ ${CONTINUE:-y} == "y" ]; then
         log_term 1 "\nChecking in changes to '${_FILE}' for \"${_REPOSITORY}\"." -e
         log_term 3 "File: '${BASH_SOURCE[0]}' Line: '${LINENO}'"
-        cd "${REPOSITORY_PATH}/${_REPOSITORY}" && git add ${_FILE}
-        cd "${REPOSITORY_PATH}/${_REPOSITORY}" && git commit -m "${_MESSAGE} [skip ci]"
-        cd "${REPOSITORY_PATH}/${_REPOSITORY}" && git push
+        if ! git diff-files --quiet --ignore-submodules --; then
+            # git diff-files --name-status -r --ignore-submodules --
+            cd "${REPOSITORY_PATH}/${_REPOSITORY}" && git add ${_FILE}
```
Comment (gozer) [inline bin/git_functions.sh:598]: Note, one can use
```
git -C "${REPOSITORY_PATH}/${_REPOSITORY}" add ${_FILE}
```

Instead of
```
cd "${REPOSITORY_PATH}/${_REPOSITORY}" && git ...
```

File: bin/git_functions.sh [hunk 3]
```diff
@@ -936,6 +946,13 @@ repository_setup_release () {
         edit_deploy_templates "${_RELEASE}"
     fi
 
+    # Update the pinned version number to the current ${_RELEASE}
+    #+ for released Trraform modules
```
Comment (gozer) [inline bin/git_functions.sh]: Typos and stray '+'
```
# for released Terraform modules
```

File: bin/git_functions.sh (hunk 2 above)
Comment (tinnightcap) [reply bin/git_functions.sh:598]: So noted.

File: release.sh [hunk 4]
```diff
@@ -232,8 +232,7 @@ release_build_repositories () {
     fi
     log_term 1 "\n${COMMAND} \"${#BUILD_REPOSITORIES[*]}\" repositories at \"${_RELEASE}\"." -e
     log_term 3 "File: '${BASH_SOURCE[0]}' Line: '${LINENO}'"
-    parallel --no-notice --output-as-files --results logs --progress --jobs "${#BUILD_REPOSITORIES[@]}" "${AWS_VAULT_EXEC_MAIN[@]}" "${COMMAND}" '{1}' "${_RELEASE}" ::: "${BUILD_REPOSITORIES[@]}"; _RV=$?
-#    parallel --no-notice --output-as-files --results logs --progress --jobs 4 "${AWS_VAULT_EXEC_MAIN[@]}" "${COMMAND}" '{1}' "${_RELEASE}" ::: "${BUILD_REPOSITORIES[@]}"; _RV=$?
```
Comment (gozer) [inline release.sh:236]: Commented out code generally doesn't belong in source-control

File: bin/git_functions.sh (hunk 3 above)
Comment (tinnightcap) [reply bin/git_functions.sh]: That is not a stray +, that is an old idiom to illustrate that the comment carries to the following line while being able to stay inline within an 80 char term limit.

Comment (gozer) [reply bin/git_functions.sh]: Really? I didn't know that idiom, consider me educated!

However, Terraform is still spelled Terraform and not Trraform ;-p

File: release.sh (hunk 4 above)
Comment (tinnightcap) [reply release.sh:236]: That comment was already removed, reload the PR

**Review by gozer — APPROVED** [review]
